stages:
  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/config.py
      - config.ini
      - data/raw/train.csv
    outs:
      - models/model.joblib
    metrics:
      - metrics.json
